apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: db
type: Opaque
stringData:
  POSTGRES_USER: "todolist_user"
  POSTGRES_PASSWORD: "todolist_password"
  POSTGRES_DB: "todolist"