apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-localhost-cert
  namespace: todolist
spec:
  secretName: app-localhost-tls
  duration: 2160h
  renewBefore: 360h
  commonName: app.localhost
  dnsNames:
    - app.localhost
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
