apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todolist
data:
  APP_NAME: "backend-todolist"
  APP_VERSION: "1.0.0"
  DB_HOST: "postgres.db.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "todolist"