apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todolist
spec:
  selector:
    app: frontend  # Sélectionne les pods avec l'étiquette app=frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
