apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: todolist-pod-manager
  namespace: todolist
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch"] 
