apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todolist-pod-manager-binding
  namespace: todolist
subjects: # On associe le Role au ServiceAccount
  - kind: ServiceAccount
    name: todolist-sa
    namespace: todolist
roleRef:
  kind: Role
  name: todolist-pod-manager
  apiGroup: rbac.authorization.k8s.io
